### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by taniadaniela** [taniadaniela/n1-agapanthus#1]
- [x] Add round red button for new e-mail and place it on the bottom right corner.
- [x] Change search box placeholder color to white.
- [x] Add different colors to sidebar icons
- [x] Add box shadow to panel.
- [x] Change search icon on search box to white.

**Comment by taniadaniela** [comment]
Thanks to @andrew-anguiano and @edipox for the contribution to finish the todo list.
